/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const SHUFFLE_ROUNDS_MINIMAL: number
export const SHUFFLE_ROUNDS_MAINNET: number
export declare function shuffleList(activeIndices: Uint32Array, seed: Uint8Array, rounds: number): Uint32Array
export declare function unshuffleList(activeIndices: Uint32Array, seed: Uint8Array, rounds: number): Uint32Array
export declare function asyncShuffleList(activeIndices: Uint32Array, seed: Uint8Array, rounds: number): Promise<Uint32Array>
export declare function asyncUnshuffleList(activeIndices: Uint32Array, seed: Uint8Array, rounds: number): Promise<Uint32Array>
export declare function computeProposerIndexElectra(effectiveBalanceIncrements: Uint16Array, activeIndices: Uint32Array, seed: Uint8Array, maxEffectiveBalanceElectra: number, effectiveBalanceIncrement: number, rounds: number): number
export declare function computeSyncCommitteeIndicesElectra(syncCommitteeSize: number, seed: Uint8Array, activeIndices: Uint32Array, effectiveBalanceIncrements: Uint16Array, maxEffectiveBalanceElectra: number, effectiveBalanceIncrement: number, rounds: number): Uint32Array
export declare class ComputeShuffledIndex {
  constructor(seed: Uint8Array, indexCount: number, rounds: number)
  get(index: number): number
}
